import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {GetStaticProps} from "next";
import {SurahCard} from "../components/SurahCard";
import {ISurah} from "../interfaces/interfaces";


export interface SurahInd {
  nomor: number
  nama: string
  nama_latin: string
  jumlah_ayat: number
  tempat_turun: string
  arti: string
  deskripsi: string
  audio: string
}

export interface Surah {
  number: number
  name: string
  latinName: string
  verseCount: number
  revelationPlace: string
  meaning: string
  description: string
  audio: string
}


export interface HomeProps { surahList: ISurah[] };

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const res = await fetch('https://equran.id/api/surat')
  const data = await res.json()

  return {
    props: { surahList: data.map((surah: SurahInd) => {
      return {
        number: surah.nomor,
        name: surah.nama,
        latinName: surah.nama_latin,
        verseCount: surah.jumlah_ayat,
        revelationPlace: surah.tempat_turun,
        meaning: surah.arti,
        description: surah.deskripsi,
        audio: surah.audio
      }
      }) }
  }
}

export default function Home({ surahList }: HomeProps) {
  console.log(surahList)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Al-Quran
        </h1>
        {surahList.map((surah) => <SurahCard key={surah.number} surah={surah} />)}
      </main>
    </>
  )
}
